version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    
    environment:
      PORT: 3002
    
    ports:
      - 3002:3002

    networks:
      - backend
      - frontend
    restart: always

networks:
  backend:
    external: true
  frontend:
    external: true