version: '3'
services:
  compiler:
    container_name: compiler
    build:
      context: .
      dockerfile: Dockerfile
    
    environment:
      PORT: 3002
      DOCKER_HOST: 10.10.10.246
    
    ports:
      - 3002:3002

    restart: always
networks_mode: host