networks:
  backend:
      external: true
services:
  compiler:
    container_name: compiler
    build:
      context: .
      dockerfile: Dockerfile 
    privileged: true
    environment:
      PORT: ${PORT}
      RMQUSER: ${RMQUSER}
      RMQPASS: ${RMQPASS}
      RMQHOST: ${RMQHOST} 
      RMQNAME: ${RMQNAME}  
      BACKEND_URL: ${BACKEND_URL} 
      JWT_SECRET: ${JWT_SECRET} 
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.services.compiler-api.loadbalancer.server.port: "3003"
      traefik.http.services.compiler-api.loadbalancer.server.scheme: "http"
      traefik.http.routers.compiler-api-https.entrypoints: "websecure"
      traefik.http.routers.compiler-api-https.rule: "Host(`codespace-compiler.srv-demo-2.home.unixvextor.com`)"
      traefik.http.routers.compiler-api-https.tls: "true"
      traefik.http.routers.compiler-api-https.tls.certresolver: "cloudflare"
    networks: 
      - backend
