name: Deployment

on:
  push:
    branches: ["dev"]
jobs:
  deploy:
    runs-on: self-hosted
    if: github.event_name == 'push'
    steps:
      - name: Clone Repo 🤖
        uses: actions/checkout@v3
      - name: Set Environment Variables 🔠
        env:
          RMQUSER: ${{ secrets.RMQUSER }}
          RMQPASS: ${{ secrets.RMQPASS }}
          RMQHOST: ${{ secrets.RMQHOST }}
          REDISHOST: ${{ secrets.REDISHOST }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          LEARNIFY_TOKEN_API: ${{ secrets.LEARNIFY_TOKEN_API }}
        run: |
          echo "JWT_SECRET=$JWT_SECRET" >> .env
          echo "RMQUSER=$RMQUSER" >> .env
          echo "RMQPASS=$RMQPASS" >> .env
          echo "RMQHOST=$RMQHOST" >> .env
          echo "REDISHOST=$REDISHOST" >> .env
          echo "BACKEND_URL=$BACKEND_URL" >> .env
          echo "LEARNIFY_TOKEN_API=$LEARNIFY_TOKEN_API" >> .env

      - name: Clear Cache 🫧
        run: |
          docker stop compiler || true
          docker rm compiler || true
          docker rmi compiler-compiler:latest || true

      - name: Run Image ✅
        run: |
          docker compose -f docker-compose.prod.yaml up -d

      - name: Message ✉️
        uses: fjogeleit/http-request-action@v1
        with:
          timeout: 60000
          url: ${{ secrets.DISCORD_WEBHOOK }}
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"content": "CE PROJECT Compiler Build ✅","embeds": [{"title": "Compiler URL","description": "https://codespace-compiler.srv-demo-2.home.unixvextor.com"}]}'
