name: Deployment

on: 
    push: 
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Clone Repo 🤖
              uses: actions/checkout@v3
            
            - name: free disk space
              run: |
                echo ${{ secrets.HOST_PASS }} | sudo -S su
                sudo swapoff -a
                sudo rm -f /swapfile
                sudo apt clean
                df -h
            
            - name: Clear Cache 🫧
              run: |
                docker stop compiler || true
                docker rm compiler || true
                docker rmi compiler-compiler:latest || true
            
            - name: Run Image ✅
              run: |
                docker compose up -d
            
            - name: Message ✉️
              uses: fjogeleit/http-request-action@v1
              with:
                timeout: 60000
                url: 'https://discord.com/api/webhooks/1205020256087711745/vgorLb_Eot-0F5fQLTcA-vLX2s4C7A6YRzYBcqBiePzzyfT004bsw-5UhUfqIvlFPTIH'
                method: 'POST'
                customHeaders: '{"Content-Type": "application/json"}'
                data: '{"content": "CEPP Backend Build ✅","embeds": [{"title": "Backend url","description": "https://compiler-api.unixvextor.com"}]}'